baseURL = "http://localhost:8080"
publishDir = "docs"
languageCode = "ja-jp"
title = "Team Enu"
theme = "team-enu-theme"

# 強調表示オプション
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writeups"
url = "/writeups/"
weight = 2

[params.homepage_meta_tags]
# .Site.Params.homepage_meta_tags.meta_description

# .Site.Params.homepage_meta_tags.meta_og_title
  meta_og_title = 'Team Enu PR site' 

# .Site.Params.homepage_meta_tags.meta_og_type
  meta_og_type = 'website'
  
# .Site.Params.homepage_meta_tags.meta_og_url
  meta_og_url = 'http://localhost:8080'
  
# .Site.Params.homepage_meta_tags.meta_og_image
  meta_og_image = 'team-enu.png'
  
# .Site.Params.homepage_meta_tags.meta_og_description
  meta_og_description = 'Team Enu PR site' 
  
# .Site.Params.homepage_meta_tags.meta_twitter_card
  meta_twitter_card = 'summary'
  
# .Site.Params.homepage_meta_tags.meta_twitter_site
  # meta_twitter_site =
  
# .Site.Params.homepage_meta_tags.meta_twitter_creator
  # meta_twitter_creator =
  