baseURL = "https://localhost:8080"
publishDir = "docs"
languageCode = "ja-jp"
title = "Team Enu"
theme = "hugo-whisper-theme"

# 強調表示オプション
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writeups"
url = "/writeups/"
weight = 2

[params]
  [params.logo]
      mobile = "team-enu.png"
      standard  = "team-enu.png"